config/routes.rb
CodeInsight::Application.routes.draw do

  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/about"
  
  

  match '/signup',  to:'users#new', via:'get'
  match '/users/*username/edit', to:'users#edit', via:'get'
  match '/signin',  to:'sessions#new',  via:'get'
  match '/signout', to:'sessions#destroy', via:'delete'
  match '/testing', to:'static_pages#testing', via:'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates( :username, presence: true , length: {maximum:50 },
					uniqueness: {case_sensitive:false} )
	validate :username_cannot_have_whitespaces
	validates( :name, presence:true , length: {maximum:100} )
	validates(:password, presence:true, length: {minimum:6} )
	validates(:email, presence:true,
				format: {with: VALID_EMAIL_REGEX},
				uniqueness: {case_sensitive:false})

	has_secure_password

	before_save do
					self.username=username.downcase
					self.email=email.downcase 
				end

	before_create :create_remember_token
	def username_cannot_have_whitespaces
		if(self.username==nil)
			return
		end

		if(self.username.to_s.gsub(/\s+/, "").length==0)
			return #since this has been checked in presence validation..
		end
		#s = "I have white space".delete(' ')
		if(self.username.to_s.gsub(/\s+/, "").length != self.username.to_s.length )
			errors.add(:username,"Cannot have whitespaces")
		end  
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token=User.hash(User.new_remember_token)
		end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user=User.find_by(username: params[:session][:username].downcase)
		if(user && user.authenticate(params[:session][:password]))
			sign_in user
			#as of now
			flash[:success]="You have been successfully signed in"
			redirect_to root_url
		else
			flash.now[:error]="Invalid username/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		flash[:success]="u ve been logged out"
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def testing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper

	before_action :signed_in_user, only: [:edit,:update]
	#before_action :correct_user,	only:[:edit,:update]
	def new
		@user=User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			sign_in @user
			flash.now[:success]='Welcome to CodeInsights'
		else
			render 'new'
		end
	end

	def show
		@user=User.find(params[:id])
	end
	def edit
		$username=params[:username]
		@user=User.find_by(username:params[:username])
	end

	def update
		@user=User.find(params[:id])
		if @user.update_attributes(user_params_for_update)
			flash[:success]='Profile updated'
			redirect_to @user
		else
			render 'edit'
		end
	end

	private

		def user_params
			params.require(:user).permit(:username,:name,:email,:password,:password_confirmation)
		end

		def user_params_for_update
			params.require(:user).permit(:name,:email,:password,:password_confirmation)
		end

		#before filters

		def signed_in_user
			redirect_to signin_url, notice: "Please Sign in." unless signed_in?
		end

		def correct_user
			@user=User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "CodeInsight"
		if(page_title.empty?)
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token=User.new_remember_token
		cookies.permanent[:remember_token]=remember_token
		user.update_attribute(:remember_token,User.hash(remember_token))
		self.current_user=user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user=nil
	end

	def current_user=(user)
		@current_user=user
	end

	def current_user
		remember_token=User.hash(cookies[:remember_token] )	
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user==current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<script >
		function toggleSlider()
		{

			if(document.getElementById("slider").style.maxHeight=="0px")
				document.getElementById("slider").style.maxHeight="500px";
			else
				document.getElementById("slider").style.maxHeight='0px';
		}
		//document.getElementById('slider').classList.toggle('closed');
	</script>
	<script type="text/javascript">
		$(document).ready(function(){

		$("#details1").hide();
		$("#toggler").hover( function() {

			$("#slider").slideToggle('2000',"linear", function () {
        		// Animation complete.
    			});
			});
		});
	</script>
	<div id="header-contents">

	</div>
	<div id="toggler">
		
	
		<div id="slider" class="slider">
			<button>Sign in</button>
			<br>
			<button>Sign up</button>
		</div>
		<div id="toggler-bar"
	    	style="background-color:green; min-width:10px;">
	    
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body style="min-width:1300px;position:relative;background:  url(https://cdn.mxpnl.com/cache/edaeb8e0378efb274b717d49aa5db114/images/static/purple_grid.png) #323355; /*background: url(/assets/back1.jpg);background-repeat:no-repeat;background-size:100% */">
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key,value| %>
			<div class="alert alert-<%= key %>"><%=value %> </div>
		<% end %>
		<%= yield %>
		<%= render 'shared/sidePanel' %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/layouts/old_header.html.erb
<header>
	<div id='authentication-div'>
		<% if signed_in? %>
			<div id="signed-in-div">
				<%= image_tag('default_profile_pic.png',alt:current_user.username,
						id:'profile-thumbnail') %>
				<div>
					<%= link_to current_user.username, 
						"#{root_url}users/#{current_user.username}/edit" %>
						<br>
					<%= link_to "Sign out", signout_path ,method:"delete"%>
				</div>
			</div>
		<% else %>
			<div id="guest-div">
				<li><%= link_to "Sign in", signin_path %></li>
				<li><%= link_to "Register yourself", signup_path %></li>
			</div>
		<% end %>
	</div>

	<div id='header-center'>
		
		<div style="width:100%;text-align:center;opacity:0.5;z-index:-5;">
			<h2>CodeInsight</h2>
		</div>
		
		<div class="navigation-bar	">
			<div class="center-tabs" >
				<ul class="">
					<li><%= link_to "Tutorial", '#' %></li>
					<li><%= link_to "Compete", '#' %></li>
					<li><%= link_to "Practice",'#' %></li>
				</ul>
			</div>
		</div>
	</div>

	<div id='logo-div'>
		<%= link_to image_tag("logo.png",alt:"CodeInsight",id:"site-logo"), root_url %>
	</div>
</header>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error" >
			The form contains <%= pluralize(@user.errors.count,"error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li>* <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title ,'About') %>
<h1>About Us</h1>
<p>CodeInsight is an initiative by some coding enthusiasts of <a href="http://www.nitw.ac.in">NIT-Warangal</a> to promote the art of programming.</p>

app/views/static_pages/home.html.erb
<% provide(:title,'Home') %>
<h1>Home</h1>
<p>Welcome to CodeInsight</p>

app/views/static_pages/testing.html.erb
<% provide(:title,'Home') %>
<h1>Home</h1>
<p>Welcome to CodeInsight</p>
<div class="timeline-container" >
	<div class="middle-divider">

	</div>
	<% (0..2).each do |i|%>
	<div class="line" id="line<%=i%>">
		<div class="left-field">
			<div class="left-wrapper ">
				<div class="right-arrow" id="rarrow<%=i%>">
				</div>
				<div  class="left-info wrapword" id="linfo<%=i%>" style="text-align:center;padding:10px;">
					COMPETE
				</div>
			</div>
		</div>
		<div class="right-field" id="rf">
			<div class="right-wrapper">
				<div class="left-arrow" id="larrow<%=i%>">
				</div> 
				<div id="card-container"class="right-info wrapword " style="position:relative;">
					<div class="card-front wrapword " id="cf<%=i%>">
						=====right-info>>>>>>>>>>>>>>>>>><br>
						=====right-info>>>>>>>>>>>>>>>>>><br>
						=====right-info>>>>>>>>>>>>>>>>>><br>
						=====right-info>>>>>>>>>>>>>>>>>><br>
					</div>
					<div class="card-back wrapword " id="cb<%=i%>" 
						style="position:absolute;top:0px;left:0px;z-index:-2;">
						back card<br>
						back card<br>
						back card<br>
						back card
					</div>
				</div>
			</div>
		</div>
	</div>

	<% end %>

	<script>
		window.onresize=function(){
			<% (0..5).each do |i|%>
				h=document.getElementById("line<%=i%>").clientHeight;
				document.getElementById("larrow<%=i%>").style.marginTop=(h/2 -  13)+"px";
				document.getElementById("rarrow<%=i%>").style.marginTop=(h/2 -  13)+"px";
				hmy=document.getElementById("linfo<%=i%>").clientHeight;
				document.getElementById("linfo<%=i%>").style.marginTop=((h -  hmy)/2)+"px";
			<% end %>	
		};
		<% (0..5).each do |i|%>
			h=document.getElementById("line<%=i%>").clientHeight;
			document.getElementById("larrow<%=i%>").style.marginTop=(h/2 -  13)+"px";
			document.getElementById("rarrow<%=i%>").style.marginTop=(h/2 -  13)+"px";
			hmy=document.getElementById("linfo<%=i%>").clientHeight;
			document.getElementById("linfo<%=i%>").style.marginTop=((h -  hmy)/2)+"px";
			h=document.getElementById("cf<%=i%>").clientHeight;
			document.getElementById("cb<%=i%>").style.height=(h-20)+"px";
		<% end %>
	</script>
</div>

app/views/users/edit.html.erb
<% provide(:title,"edit profile of #{$username}") %> 
<h1>Edit profile => <%=$username %></h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>	

			<%= f.submit "Create my account", class:"btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title,'Sign up') %> 
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages' %>

			<%= f.label :username %>
			<%= f.text_field :username %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>	

			<%= f.submit "Create my account", class:"btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<table>
	<tr>
		<td>Username:</td>
		<td><%= @user.username %></td>
	</tr>
	<tr>
		<td>Name:</td>
		<td><%= @user.name %></td>
	</tr>
	<tr>
		<td>Email</td>
		<td><%= @user.email%></td>
	</tr>
</table>